# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marble's Power Corner
email: marcus.blennegard@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog about my journey as a Microsoft 365 Solutions Architect.
  I will be writing mainly guides and how-to's about Microsoft's Power Platform, including Power Apps and Power Automate.
  There might also be a few other articles and topics as well, e.g. SharePoint, PowerShell, Azure etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mblennegard
github_username:  mblennegard
linkedin_username: mblennegard

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: G-7D747F8N7Q

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
